### ISSUE TITLE
Timeout with kodi 17.

### ISSUE THREAD

**Issue by mac1202** [metal3d/idok#12]
With kodi 17, i can no longer stream local file to kodi, I got this error in kodi.log 
`ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for http://192.168.1.1:8080/test.mp4`

Sending URL to kodi still work.

**Comment by mac1202** [comment]
Nevermind the problem come from my firewall setup.

**Comment by metal3d** [comment]
BTW you may use SSH tunnel mode that is implemented in idok. 

Note to myself:  precise errors and solutions that can appear.

**Comment by mac1202** [comment]
SSH tunnel never worked for me as reported here https://github.com/metal3d/idok/issues/8
